apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-deployment
  labels:
    app: project2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project2-deployment
  template:
    metadata:
      labels:
        app: project2-deployment
    spec:
      containers:
        - name: project2-deployment
          image: imaheshm85/customweb:2.1
          ports:
            - containerPort: 80
